const cards = [
  {
    id: "actionA",
    word: "cry",
    translation: "плакать",
    image: "assets/images/cards/cry.jpg",
    audioSrc: "assets/audio/cry.mp3",
  },
  {
    id: "actionA",
    word: "dance",
    translation: "танцевать",
    image: "assets/images/cards/dance.jpg",
    audioSrc: "assets/audio/dance.mp3",
  },
  {
    id: "actionA",
    word: "dive",
    translation: "нырять",
    image: "assets/images/cards/dive.jpg",
    audioSrc: "assets/audio/dive.mp3",
  },
  {
    id: "actionA",
    word: "draw",
    translation: "рисовать",
    image: "assets/images/cards/draw.jpg",
    audioSrc: "assets/audio/draw.mp3",
  },
  {
    id: "actionA",
    word: "fish",
    translation: "ловить рыбу",
    image: "assets/images/cards/fish.jpg",
    audioSrc: "assets/audio/fish.mp3",
  },
  {
    id: "actionA",
    word: "fly",
    translation: "летать",
    image: "assets/images/cards/fly.jpg",
    audioSrc: "assets/audio/fly.mp3",
  },
  {
    id: "actionA",
    word: "hug",
    translation: "обнимать",
    image: "assets/images/cards/hug.jpg",
    audioSrc: "assets/audio/hug.mp3",
  },
  {
    id: "actionA",
    word: "jump",
    translation: "прыгать",
    image: "assets/images/cards/jump.jpg",
    audioSrc: "assets/audio/jump.mp3",
  },
  {
    id: "actionB",
    word: "open",
    translation: "открывать",
    image: "assets/images/cards/open.jpg",
    audioSrc: "assets/audio/open.mp3",
  },
  {
    id: "actionB",
    word: "play",
    translation: "играть",
    image: "assets/images/cards/play.jpg",
    audioSrc: "assets/audio/play.mp3",
  },
  {
    id: "actionB",
    word: "point",
    translation: "указывать",
    image: "assets/images/cards/point.jpg",
    audioSrc: "assets/audio/point.mp3",
  },
  {
    id: "actionB",
    word: "ride",
    translation: "ездить",
    image: "assets/images/cards/ride.jpg",
    audioSrc: "assets/audio/ride.mp3",
  },
  {
    id: "actionB",
    word: "run",
    translation: "бегать",
    image: "assets/images/cards/run.jpg",
    audioSrc: "assets/audio/run.mp3",
  },
  {
    id: "actionB",
    word: "sing",
    translation: "петь",
    image: "assets/images/cards/sing.jpg",
    audioSrc: "assets/audio/sing.mp3",
  },
  {
    id: "actionB",
    word: "skip",
    translation: "пропускать, прыгать",
    image: "assets/images/cards/skip.jpg",
    audioSrc: "assets/audio/skip.mp3",
  },
  {
    id: "actionB",
    word: "swim",
    translation: "плавать",
    image: "assets/images/cards/swim.jpg",
    audioSrc: "assets/audio/swim.mp3",
  },

  {
    id: "animalA",
    word: "cat",
    translation: "кот",
    image: "assets/images/cards/cat.jpg",
    audioSrc: "assets/audio/cat.mp3",
  },
  {
    id: "animalA",
    word: "chick",
    translation: "цыплёнок",
    image: "assets/images/cards/chick.jpg",
    audioSrc: "assets/audio/chick.mp3",
  },
  {
    id: "animalA",
    word: "chicken",
    translation: "курица",
    image: "assets/images/cards/chicken.jpg",
    audioSrc: "assets/audio/chicken.mp3",
  },
  {
    id: "animalA",
    word: "dog",
    translation: "собака",
    image: "assets/images/cards/dog.jpg",
    audioSrc: "assets/audio/dog.mp3",
  },
  {
    id: "animalA",
    word: "horse",
    translation: "лошадь",
    image: "assets/images/cards/horse.jpg",
    audioSrc: "assets/audio/horse.mp3",
  },
  {
    id: "animalA",
    word: "pig",
    translation: "свинья",
    image: "assets/images/cards/pig.jpg",
    audioSrc: "assets/audio/pig.mp3",
  },
  {
    id: "animalA",
    word: "rabbit",
    translation: "кролик",
    image: "assets/images/cards/rabbit.jpg",
    audioSrc: "assets/audio/rabbit.mp3",
  },
  {
    id: "animalA",
    word: "sheep",
    translation: "овца",
    image: "assets/images/cards/sheep.jpg",
    audioSrc: "assets/audio/sheep.mp3",
  },

  {
    id: "animalB",
    word: "bird",
    translation: "птица",
    image: "assets/images/cards/bird.jpg",
    audioSrc: "assets/audio/bird.mp3",
  },
  {
    id: "animalB",
    word: "fish",
    translation: "рыба",
    image: "assets/images/cards/fish1.jpg",
    audioSrc: "assets/audio/fish.mp3",
  },
  {
    id: "animalB",
    word: "frog",
    translation: "жаба",
    image: "assets/images/cards/frog.jpg",
    audioSrc: "assets/audio/frog.mp3",
  },
  {
    id: "animalB",
    word: "giraffe",
    translation: "жирафа",
    image: "assets/images/cards/giraffe.jpg",
    audioSrc: "assets/audio/giraffe.mp3",
  },
  {
    id: "animalB",
    word: "lion",
    translation: "лев",
    image: "assets/images/cards/lion.jpg",
    audioSrc: "assets/audio/lion.mp3",
  },
  {
    id: "animalB",
    word: "mouse",
    translation: "мышь",
    image: "assets/images/cards/mouse.jpg",
    audioSrc: "assets/audio/mouse.mp3",
  },
  {
    id: "animalB",
    word: "turtle",
    translation: "черепаха",
    image: "assets/images/cards/turtle.jpg",
    audioSrc: "assets/audio/turtle.mp3",
  },
  {
    id: "animalB",
    word: "dolphin",
    translation: "дельфин",
    image: "assets/images/cards/dolphin.jpg",
    audioSrc: "assets/audio/dolphin.mp3",
  },

  {
    id: "clothes",
    word: "skirt",
    translation: "юбка",
    image: "assets/images/cards/skirt.jpg",
    audioSrc: "assets/audio/skirt.mp3",
  },
  {
    id: "clothes",
    word: "pants",
    translation: "брюки",
    image: "assets/images/cards/pants.jpg",
    audioSrc: "assets/audio/pants.mp3",
  },
  {
    id: "clothes",
    word: "blouse",
    translation: "блузка",
    image: "assets/images/cards/blouse.jpg",
    audioSrc: "assets/audio/blouse.mp3",
  },
  {
    id: "clothes",
    word: "dress",
    translation: "платье",
    image: "assets/images/cards/dress.jpg",
    audioSrc: "assets/audio/dress.mp3",
  },
  {
    id: "clothes",
    word: "boot",
    translation: "ботинок",
    image: "assets/images/cards/boot.jpg",
    audioSrc: "assets/audio/boot.mp3",
  },
  {
    id: "clothes",
    word: "shirt",
    translation: "рубашка",
    image: "assets/images/cards/shirt.jpg",
    audioSrc: "assets/audio/shirt.mp3",
  },
  {
    id: "clothes",
    word: "coat",
    translation: "пальто",
    image: "assets/images/cards/coat.jpg",
    audioSrc: "assets/audio/coat.mp3",
  },
  {
    id: "clothes",
    word: "shoe",
    translation: "туфли",
    image: "assets/images/cards/shoe.jpg",
    audioSrc: "assets/audio/shoe.mp3",
  },

  {
    id: "emotions",
    word: "sad",
    translation: "грустный",
    image: "assets/images/cards/sad.jpg",
    audioSrc: "assets/audio/sad.mp3",
  },
  {
    id: "emotions",
    word: "angry",
    translation: "сердитый",
    image: "assets/images/cards/angry.jpg",
    audioSrc: "assets/audio/angry.mp3",
  },
  {
    id: "emotions",
    word: "happy",
    translation: "счастливый",
    image: "assets/images/cards/happy.jpg",
    audioSrc: "assets/audio/happy.mp3",
  },
  {
    id: "emotions",
    word: "tired",
    translation: "уставший",
    image: "assets/images/cards/tired.jpg",
    audioSrc: "assets/audio/tired.mp3",
  },
  {
    id: "emotions",
    word: "surprised",
    translation: "удивлённый",
    image: "assets/images/cards/surprised.jpg",
    audioSrc: "assets/audio/surprised.mp3",
  },
  {
    id: "emotions",
    word: "scared",
    translation: "испуганный",
    image: "assets/images/cards/scared.jpg",
    audioSrc: "assets/audio/scared.mp3",
  },
  {
    id: "emotions",
    word: "smile",
    translation: "улыбка",
    image: "assets/images/cards/smile.jpg",
    audioSrc: "assets/audio/smile.mp3",
  },
  {
    id: "emotions",
    word: "laugh",
    translation: "смех",
    image: "assets/images/cards/laugh.jpg",
    audioSrc: "assets/audio/laugh.mp3",
  },
];

export default cards;
